In [2]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
import seaborn as sns

----------
## Importing Data

In [3]:
df = pd.read_csv("food_coded.csv")

In [1]:
df.columns

NameError: name 'df' is not defined

Todo:
- make stuff 0 based?
- Hot encode: gender, breakfast, coffee (7), comfort_food_reason (10), cuisine (12)
- split and give standard format?
- (11) is already ordinal? but switch order to make it more intuitive

In [4]:
from ydata_profiling import ProfileReport

profile = ProfileReport(df, title="Profiling Report")
profile.to_file("report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/61 [00:00<?, ?it/s]
100%|██████████| 61/61 [00:00<00:00, 162.78it/s]A

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [7]:
pd.read_csv("other_class.csv")

,GPA,calories_chicken,calories_day,calories_scone,cook,eating_out,ethnic_food,exercise,father_education,fruit_day,...,fav_cuisine_none,fav_cuisine_spanish_mexican,ideal_diet_balance,ideal_diet_current_diet,ideal_diet_eat_healthier,ideal_diet_home_cooked_organic,ideal_diet_less_sugar,ideal_diet_more_protein,ideal_diet_portion_control,ideal_diet_unclear
0,0.807778,3,3,3,3,2,4,1,2,4,...,0,0,1,0,0,0,0,0,0,0
1,0.611111,4,4,3,1,2,5,2,2,5,...,0,0,0,1,0,0,0,0,0,0
2,0.555556,2,3,3,2,2,5,3,2,4,...,0,0,0,0,1,0,0,0,0,0
3,0.722222,4,2,3,1,2,4,1,4,4,...,0,0,0,0,1,0,0,0,0,0
4,0.888889,3,3,3,2,2,5,1,4,4,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,0.722222,3,4,3,3,2,4,2,4,5,...,0,0,0,1,0,0,0,0,0,0
115,0.444444,1,2,2,3,4,3,2,5,4,...,0,1,0,0,0,1,0,0,0,0
116,0.934444,4,1,3,3,3,5,2,5,4,...,0,0,0,0,1,0,0,0,0,0
117,0.444444,4,4,3,3,5,2,1,3,5,...,0,0,0,1,0,0,0,0,0,0
118,0.944444,2,1,2,3,1,3,2,4,3,...,0,1,1,0,0,0,0,0,0,0

In [9]:
continuous_cols = [
  'GPA',
  'weight'
]

binary_cols = [
  'Gender',
  'breakfast',
  'coffee',
  'drink',
  'fries',
  'soup',
  'sports',
  'vitamins'
]

ordinal_cols = [
  'calories_day',
  'cook',
  'eating_out',
  'ethnic_food',
  'exercise',
  'fruit_day',
  'greek_food',
  'indian_food',
  'italian_food',
  'persian_food',
  'thai_food',
  'nutritional_check',
  'pay_meal_out',
  'self_perception_weight',

  'veggies_day',
  'father_education',
  'mother_education',
  'grade_level',
  'parents_cook'
]

nominal_cols = [
  'healthy_feeling',
  'life_rewarding',
  'comfort_food_reasons_coded',
  'cuisine',
  'diet_current_coded',
  'eating_changes_coded',
  'eating_changes_coded1',
  'employment',
  'fav_cuisine_coded',
  'fav_food',
  'ideal_diet_coded',
  'marital_status',
  'on_off_campus'
]

special_case_cols = [
  'income'
]

text_cols = [


  'diet_current',
  'eating_changes',

  
  'healthy_meal',
  'ideal_diet'

]

categorical_text_cols = [
  'comfort_food',
  'comfort_food_reasons',
  'meals_dinner_friend',
  'type_sports',
  'fav_cuisine', 
  'food_childhood',
  'father_profession',
  'mother_profession',
]

freetext_cols = text_cols + categorical_text_cols

multiple_choice_cols = [
  'calories_chicken',
  'calories_scone',
  'tortilla_calories',
  'turkey_calories',
  'waffle_calories'
]

In [ ]:
multiple_choice_mappings = {
    'calories_chicken': {
        265: 1,
        430: 2,
        610: 3,
        720: 4
    },
    'calories_scone': {
        107: 1,
        315: 2,
        420: 3,
        980: 4
    },
    'tortilla_calories': {
        580: 1,
        725: 2,
        940: 3,
        1165: 4
    },
    'turkey_calories': {
        345: 1,
        500: 2,
        690: 3,
        850: 4
    },
    'waffle_calories': {
        575: 1,
        760: 2,
        900: 3,
        1315: 4
    }
}

In [22]:
df[continuous_cols]

       GPA                    weight  healthy_feeling  life_rewarding
0      2.4                       187                2             1.0
1    3.654                       155                5             1.0
2      3.3  I'm not answering this.                 6             7.0
3      3.2             Not sure, 240                7             2.0
4      3.5                       190                6             1.0
..     ...                       ...              ...             ...
120    3.5                       156                5             7.0
121      3                       180                5             7.0
122  3.882                       120                6            10.0
123      3                       135                1             1.0
124    3.9                       135                3             5.0

[125 rows x 4 columns]

In [23]:
df['life_rewarding'].value_counts()

life_rewarding
1.0     23
8.0     18
3.0     15
7.0     14
2.0     13
9.0     11
5.0     10
10.0    10
4.0      6
6.0      4
Name: count, dtype: int64

In [ ]:
pd.to_numeric()

In [28]:
df[binary_cols].describe()

,Gender,breakfast,coffee,drink,fries,soup,sports,vitamins
count,125.000000,125.000000,125.00000,123.000000,125.000000,124.000000,123.000000,125.000000
mean,1.392000,1.112000,1.75200,1.560976,1.088000,1.217742,1.390244,1.512000
std,0.490161,0.316636,0.43359,0.498298,0.284435,0.414385,0.489800,0.501867
min,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.000000,1.000000,2.00000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,1.000000,1.000000,2.00000,2.000000,1.000000,1.000000,1.000000,2.000000
75%,2.000000,1.000000,2.00000,2.000000,1.000000,1.000000,2.000000,2.000000
max,2.000000,2.000000,2.00000,2.000000,2.000000,2.000000,2.000000,2.000000

In [36]:
df[ordinal_cols]

,calories_day,cook,eating_out,ethnic_food,exercise,fruit_day,greek_food,indian_food,italian_food,persian_food,thai_food,nutritional_check,pay_meal_out,self_perception_weight,veggies_day,father_education,mother_education,grade_level,parents_cook
0,NaN,2.0,3,1,1.0,5,5,5,5,5.0,1,5,2,3.0,5,5.0,1.0,2,1
1,3.0,3.0,2,4,1.0,4,4,4,4,4.0,2,4,4,3.0,4,2.0,4.0,4,1
2,4.0,1.0,2,5,2.0,5,5,5,5,5.0,5,4,3,6.0,5,2.0,2.0,3,1
3,3.0,2.0,2,5,3.0,4,5,5,5,5.0,5,2,2,5.0,3,2.0,4.0,4,1
4,2.0,1.0,2,4,1.0,4,4,2,5,2.0,4,3,4,4.0,4,4.0,5.0,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,4.0,3.0,2,4,2.0,5,5,3,5,3.0,5,5,4,4.0,5,4.0,3.0,4,1
121,2.0,3.0,4,3,2.0,4,1,5,5,1.0,4,3,4,4.0,5,5.0,2.0,4,3
122,NaN,3.0,3,5,2.0,4,5,5,3,5.0,5,3,4,4.0,4,5.0,1.0,3,2
123,4.0,3.0,5,2,1.0,5,1,1,5,1.0,1,4,3,2.0,3,3.0,2.0,1,2
124,NaN,NaN,1,3,2.0,3,2,2,3,2.0,2,5,3,3.0,4,4.0,3.0,3,3

In [31]:
df[ordinal_cols].describe()

,calories_day,cook,eating_out,ethnic_food,exercise,fruit_day,greek_food,indian_food,italian_food,persian_food,thai_food,nutritional_check,pay_meal_out,self_perception_weight,veggies_day,father_education,mother_education,grade_level,parents_cook
count,106.000000,122.000000,125.00000,125.000000,112.000000,125.000000,125.000000,125.000000,125.000000,124.000000,125.000000,125.000000,125.000000,124.000000,125.000000,124.000000,122.000000,125.000000,125.000000
mean,3.028302,2.786885,2.56000,3.744000,1.589286,4.224000,3.488000,3.152000,4.728000,2.806452,3.336000,3.152000,3.408000,3.120968,4.008000,3.483871,3.426230,2.376000,1.528000
std,0.639308,1.038351,1.13876,1.177093,0.665137,0.923388,1.365567,1.486802,0.587175,1.423824,1.436528,1.205204,1.040285,1.115980,1.081337,1.206243,1.170703,1.133536,0.746778
min,2.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,3.000000,2.000000,2.00000,3.000000,1.000000,4.000000,3.000000,2.000000,5.000000,2.000000,2.000000,2.000000,3.000000,2.000000,3.000000,2.000000,2.000000,1.000000,1.000000
50%,3.000000,3.000000,2.00000,4.000000,1.000000,5.000000,4.000000,3.000000,5.000000,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,2.000000,1.000000
75%,3.000000,3.000000,3.00000,5.000000,2.000000,5.000000,5.000000,5.000000,5.000000,4.000000,5.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,3.000000,2.000000
max,4.000000,5.000000,5.00000,5.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,6.000000,6.000000,5.000000,5.000000,5.000000,4.000000,5.000000

In [37]:
df[nominal_cols]

,comfort_food_reasons_coded,cuisine,diet_current_coded,eating_changes_coded,eating_changes_coded1,employment,fav_cuisine_coded,fav_food,ideal_diet_coded,marital_status,on_off_campus
0,9.0,NaN,1,1,1,3.0,3,1.0,8,1.0,1.0
1,1.0,1.0,2,1,2,2.0,1,1.0,3,2.0,1.0
2,1.0,3.0,3,1,3,3.0,1,3.0,6,2.0,2.0
3,2.0,2.0,2,1,3,3.0,3,1.0,2,2.0,1.0
4,1.0,2.0,2,3,4,2.0,1,3.0,2,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
120,NaN,1.0,2,1,3,1.0,1,1.0,6,1.0,3.0
121,NaN,NaN,2,1,3,3.0,2,1.0,5,1.0,1.0
122,NaN,NaN,2,1,3,3.0,4,1.0,2,1.0,1.0
123,NaN,1.0,1,1,8,2.0,1,3.0,6,1.0,1.0
124,NaN,3.0,1,2,5,2.0,2,1.0,3,2.0,1.0

In [14]:
df[special_case_cols]

     income
0       5.0
1       4.0
2       6.0
3       6.0
4       6.0
..      ...
120     4.0
121     2.0
122     2.0
123     4.0
124     5.0

[125 rows x 1 columns]

In [33]:
df[text_cols]

,diet_current,eating_changes,healthy_meal,ideal_diet
0,eat good and exercise,eat faster,looks not oily,being healthy
1,I eat about three times a day with some snacks...,I eat out more than usual.,"Grains, Veggies, (more of grains and veggies),...",Try to eat 5-6 small meals a day. While trying...
2,"toast and fruit for breakfast, salad for lunch...",sometimes choosing to eat fast food instead of...,usually includes natural ingredients; nonproce...,i would say my ideal diet is my current diet
3,"College diet, cheap and easy foods most nights...",Accepting cheap and premade/store bought foods,"Fresh fruits& vegetables, organic meats","Healthy, fresh veggies/fruits & organic foods"
4,I try to eat healthy but often struggle becaus...,I have eaten generally the same foods but I do...,"A lean protein such as grilled chicken, green ...",Ideally I would like to be able to eat healthi...
...,...,...,...,...
120,"My diet consists mainly of coffee, water, frui...",I have noticed there is less time for a prepar...,mainly protein and vegetables with a complex c...,My ideal diet would consist of a majority of w...
121,A college student with an imbalanced diet tryi...,Eating Pizza as an excuse when there is nothin...,"A healthy meal is a variety of food , organic ...",Eating home cooked meals everyday and being ab...
122,"Rice, oatmeal, and tea",less rice,lots of vegetables,lots of veggies
123,I try to eat as healthy as possible everyday. ...,I don't eat as much on a daily basis since com...,"A protein, a fruit, a starch, and a salad or s...",My ideal diet is the diet i am currently on. ...
124,high in protein and low in carbohydrates.,I have learned to eat more vegetables.,"a cup of rice, vegetables, and meat.","Being able to balance between sweets, vegetabl..."

In [34]:
df[categorical_text_cols]

,comfort_food,comfort_food_reasons,meals_dinner_friend,type_sports,fav_cuisine,food_childhood,father_profession,mother_profession
0,none,we dont have comfort,"rice, chicken, soup",car racing,Arabic cuisine,rice and chicken,profesor,unemployed
1,"chocolate, chips, ice cream","Stress, bored, anger","Pasta, steak, chicken",Basketball,Italian,"chicken and biscuits, beef soup, baked beans",Self employed,Nurse RN
2,"frozen yogurt, pizza, fast food","stress, sadness","chicken and rice with veggies, pasta, some kin...",none,italian,"mac and cheese, pizza, tacos",owns business,owns business
3,"Pizza, Mac and cheese, ice cream",Boredom,Grilled chicken \rStuffed Shells\rHomemade Chili,NaN,Turkish,"Beef stroganoff, tacos, pizza",Mechanic,Special Education Teacher
4,"Ice cream, chocolate, chips","Stress, boredom, cravings","Chicken Parmesan, Pulled Pork, Spaghetti and m...",Softball,Italian,"Pasta, chicken tender, pizza",IT,Substance Abuse Conselor
...,...,...,...,...,...,...,...,...
120,"wine. mac and cheese, pizza, ice cream",boredom and sadness,"pasta, fish, steak",Softball,Italian,Stromboli Mac and Cheese and Pizza,Accountant,Radiological Technician
121,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,Fried Rice \rBaked potatoes \rCurry Chicken,basketball,Mexican Food,"Isombe , Plantains and Ugali",Doctor,Public Health Advisor
122,"rice, potato, seaweed soup",sadness,"meat, rice, kimchi",none,Korean,Rice and potato,CEO of company,Real Estate manageer
123,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods","Pizza, Spaghetti, Baked Ziti",NaN,Italian,pizza and spaghetti,Store manager at Giant Eagle,Receptionist for a medical supply company
124,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.","Vegetables, Meat, and rice.",NaN,HISPANIC CUISINE.,"rice, beans, and chicken / pizza/ tenders",Journalist,House-wife

In [35]:
df[freetext_cols]

,diet_current,eating_changes,healthy_meal,ideal_diet,comfort_food,comfort_food_reasons,meals_dinner_friend,type_sports,fav_cuisine,food_childhood,father_profession,mother_profession
0,eat good and exercise,eat faster,looks not oily,being healthy,none,we dont have comfort,"rice, chicken, soup",car racing,Arabic cuisine,rice and chicken,profesor,unemployed
1,I eat about three times a day with some snacks...,I eat out more than usual.,"Grains, Veggies, (more of grains and veggies),...",Try to eat 5-6 small meals a day. While trying...,"chocolate, chips, ice cream","Stress, bored, anger","Pasta, steak, chicken",Basketball,Italian,"chicken and biscuits, beef soup, baked beans",Self employed,Nurse RN
2,"toast and fruit for breakfast, salad for lunch...",sometimes choosing to eat fast food instead of...,usually includes natural ingredients; nonproce...,i would say my ideal diet is my current diet,"frozen yogurt, pizza, fast food","stress, sadness","chicken and rice with veggies, pasta, some kin...",none,italian,"mac and cheese, pizza, tacos",owns business,owns business
3,"College diet, cheap and easy foods most nights...",Accepting cheap and premade/store bought foods,"Fresh fruits& vegetables, organic meats","Healthy, fresh veggies/fruits & organic foods","Pizza, Mac and cheese, ice cream",Boredom,Grilled chicken \rStuffed Shells\rHomemade Chili,NaN,Turkish,"Beef stroganoff, tacos, pizza",Mechanic,Special Education Teacher
4,I try to eat healthy but often struggle becaus...,I have eaten generally the same foods but I do...,"A lean protein such as grilled chicken, green ...",Ideally I would like to be able to eat healthi...,"Ice cream, chocolate, chips","Stress, boredom, cravings","Chicken Parmesan, Pulled Pork, Spaghetti and m...",Softball,Italian,"Pasta, chicken tender, pizza",IT,Substance Abuse Conselor
...,...,...,...,...,...,...,...,...,...,...,...,...
120,"My diet consists mainly of coffee, water, frui...",I have noticed there is less time for a prepar...,mainly protein and vegetables with a complex c...,My ideal diet would consist of a majority of w...,"wine. mac and cheese, pizza, ice cream",boredom and sadness,"pasta, fish, steak",Softball,Italian,Stromboli Mac and Cheese and Pizza,Accountant,Radiological Technician
121,A college student with an imbalanced diet tryi...,Eating Pizza as an excuse when there is nothin...,"A healthy meal is a variety of food , organic ...",Eating home cooked meals everyday and being ab...,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,Fried Rice \rBaked potatoes \rCurry Chicken,basketball,Mexican Food,"Isombe , Plantains and Ugali",Doctor,Public Health Advisor
122,"Rice, oatmeal, and tea",less rice,lots of vegetables,lots of veggies,"rice, potato, seaweed soup",sadness,"meat, rice, kimchi",none,Korean,Rice and potato,CEO of company,Real Estate manageer
123,I try to eat as healthy as possible everyday. ...,I don't eat as much on a daily basis since com...,"A protein, a fruit, a starch, and a salad or s...",My ideal diet is the diet i am currently on. ...,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods","Pizza, Spaghetti, Baked Ziti",NaN,Italian,pizza and spaghetti,Store manager at Giant Eagle,Receptionist for a medical supply company
124,high in protein and low in carbohydrates.,I have learned to eat more vegetables.,"a cup of rice, vegetables, and meat.","Being able to balance between sweets, vegetabl...","Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.","Vegetables, Meat, and rice.",NaN,HISPANIC CUISINE.,"rice, beans, and chicken / pizza/ tenders",Journalist,House-wife

In [18]:
df[multiple_choice_cols]

,calories_chicken,calories_scone,tortilla_calories,turkey_calories,waffle_calories
0,430,315.0,1165.0,345,1315
1,610,420.0,725.0,690,900
2,720,420.0,1165.0,500,900
3,430,420.0,725.0,690,1315
4,720,420.0,940.0,500,760
...,...,...,...,...,...
120,610,420.0,940.0,500,1315
121,265,315.0,940.0,500,1315
122,720,420.0,580.0,690,1315
123,720,420.0,940.0,500,1315
124,430,315.0,725.0,345,575

# Open-ended features where respondents list multiple items
multiple_item_text_cols = [
    'comfort_food',              # "List 3-5 comfort foods that come to mind"
    'comfort_food_reasons',      # "What are some of the reasons that make you eat comfort food? - list up to three"
    'meals_dinner_friend',       # "What would you serve to a friend for dinner?" (may list multiple dishes)
    'type_sports'                # "What type of sports are you involved?" (may list multiple sports)
]